#!/bin/bash

# Setup Script

# Check if the script was run with sudo
if [ "$(id -u)" -ne 0 ]; then
  echo "Please run the script using the 'sudo' command"
  exit 1
fi

# Download and execute the script
wget -qO- "https://raw.githubusercontent.com/teeles/kiosk/main/kiosk.sh" | bash
